language: node_js
node_js:
  - "6"
  - "8"
  - "10"

before_install:
  - npm install -g grunt-cli

# travis build  speed up
sudo: false
cache:
  directories:
    - node_modules

# scripts
script: grunt test

# hooks
notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/e369617839852624aa69'
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
