language: node_js
node_js:
  - "0.8"
  - "0.10"

before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm@latest
  - npm install -g grunt-cli

#travis build  speed up
sudo: false
cache:
  directories:
    - node_modules

# hooks
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e369617839852624aa69
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
